### ISSUE TITLE
Legend - Hiding line resets line thickness

### ISSUE THREAD

**Issue by thober35** [AnyChart/AnyChart-Android#206]
Hello,
for our line chart we increased the line thickness as suggested [here](https://github.com/AnyChart/AnyChart/issues/78#issuecomment-474686720)

`        series.stroke("function() {\n" +
                   "    return {color: this.sourceColor, thickness: 4};}");`

As you can see in the video below when the chart appears, the changed line thickness is displayed correctly. But after hiding then showing the line per legend, it has the default thickness again.

![chart1](https://user-images.githubusercontent.com/33911884/103464873-651ef600-4d37-11eb-8537-032a99978bcc.gif)

How can we make sure that the line stays at the desired thickness?

**Comment by Shestac92** [comment]
@thober35 
It happens because you have applied the stroke settings only for the default state of the series - "normal". But there are also "hovered" and "selected". In your case, they remain as default.
After the second click on the legend item, the whole series gets "hovered".
So, you need to apply the same thickness to the hovered and selected states.
The snippet below described how to achieve that:
```
        series.normal().stroke("function() {\n" + " return {color: this.sourceColor, thickness: 4};}");
        series.hovered().stroke("function() {\n" + " return {color: 'green', thickness: 4};}");
        series.selected().stroke("function() {\n" + " return {color: 'red', thickness: 4};}");
```

**Comment by thober35** [comment]
This resolved my issue. Thanks!
