### ISSUE TITLE
Customize funnel chart

### ISSUE THREAD

**Issue by Vivektilva** [AnyChart/AnyChart-Android#4]
Hey ,

Can you guide me how can I set my custom color in funnel chart..?

and one more que i have,
In funnel chart i want to show label outside and value inside ,,is that possible , can you send me code for that?

@Shestac92 @ArsenyMalkov

**Comment by Shestac92** [comment]
@Vivektilva 
You can set your custom colors for funnel chart like this:
`funnel.setPalette(new String[]{ "#fff", "#fff", "#fff", "#fff", "#fff" });` - just define your colors instead of #fff 

Showing label outside and value inside is not available as an out-of-the-box feature. But I may suggest you a little trick to implement it. We have prepared a code example for you, please try the following code - https://gist.github.com/Shestac92/26a0ad7e121db653aca924de02f90fcc

![2018-02-20 12 24 55](https://user-images.githubusercontent.com/24609062/36407383-2502b54e-1639-11e8-81dc-50536e3b7239.jpg)

I hope this will help you!

**Comment by Vivektilva** [comment]
@Shestac92 

Thank you so much this is very useful.
Your trick will help me .
