### ISSUE TITLE
Fast updating of multiple scatter charts in one layout

### ISSUE THREAD

**Issue by eliotstock** [AnyChart/AnyChart-Android#83]
Hi,

I'd like to have three scatter charts laid out on one activity, all updating in real time at about 8 Hz. I don't seem to be able to do this.

When I add the second and third chart, the first one disappears from the layout. If I remove the second and third charts, the first one starts working again, but updates are very delayed.

I noticed a bunch of mentions of JS in the API surface. Is this implemented as a WebView using Javascript? Can it keep up with new data points at 8 Hz?

Thanks.

**Comment by Shestac92** [comment]
@eliotstock 
Please, check the wiki article about [Multiple charts in a single layout](https://github.com/AnyChart/AnyChart-Android/wiki/Multiple-charts-in-a-single-layout). 
Yes, you can update the chart data at any moment. For details, you can check [this issue comment](https://github.com/AnyChart/AnyChart-Android/issues/28#issuecomment-417997179) which describes how to achieve that with the Android library.

**Comment by JavaDeveloper08** [comment]
Hi Shestac, Thank you for nica replies. 
I have more than 20 line charts. I examined "Multiple Charts in a single layout" page. In that page,we are manually adding the anycharts. But if we don't know the total chart number and it is created dynamically. Because i am getting list of departments includes data for creating charts from service. I am adding this data list to an options list in the main activity. And user choose an option  So i would like to show in same layout. and user choose another option, I must show another chart in the same layout. All of charts are line charts, but not only data changes, but also title of charts, column numbers etc. are changing in these charts. So I must create a new chart in the same layout. How can I solve this problem ? Thanks.
